spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    root: INFO
    web: TRACE
    org.springframework.web: TRACE

myenergi:
  hub.serial: 1111111111
  password: password